name: "self-hosted demo deploy"
run-name: "Deployment of demo applications"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy demo app
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: testing
        run: |
          echo teeeeeest
          echo aaaaaa >> test.txt

      - run: whoami

      - name: docker hello-world
        run: docker run hello-world
