name: "self-hosted demo deploy"
run-name: "Deployment of demo applications"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy demo app
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: create context
        run: docker context create gha-demo --docker "host=ssh://kassie@192.168.1.128"

      - name: change context
        run: docker context use gha-demo

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: docker compose up
        run: docker compose up -d
